FROM node:18.10-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY package*.json ./

USER node

COPY --chown=node:node . .

EXPOSE 3000

RUN npm install

CMD [ "npm", "start" ]
